import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

import { readTreeState, type TreeMode } from "./binding-state.js";
import { ensureTrailingNewline } from "./shared.js";

const TREE_IDENTITY_BEGIN = "<!-- BEGIN FIRST-TREE-TREE-IDENTITY -->";
const TREE_IDENTITY_END = "<!-- END FIRST-TREE-TREE-IDENTITY -->";
const TREE_IDENTITY_MARKER = "FIRST-TREE-TREE-IDENTITY:";
const TREE_REPO_MARKER = "FIRST-TREE-TREE-REPO:";
const TREE_MODE_MARKER = "FIRST-TREE-TREE-MODE:";
const TREE_PUBLISHED_URL_MARKER = "FIRST-TREE-TREE-PUBLISHED-URL:";
const TREE_IDENTITY_FILES = ["AGENTS.md", "CLAUDE.md"] as const;

export type ManagedTreeIdentity = {
  file: "AGENTS.md" | "CLAUDE.md";
  path: string;
  publishedTreeUrl?: string;
  treeMode?: TreeMode;
  treeRepoName: string;
};

export type TreeIdentityContract = {
  publishedTreeUrl?: string;
  treeMode?: TreeMode;
  treeRepoName: string;
};

type SyncAction = "created" | "updated" | "unchanged" | "skipped";

function escapeForRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

function readMarker(block: string, marker: string): string | undefined {
  const match = block.match(
    new RegExp(`^${escapeForRegExp(marker)}\\s+(?:\`(.+?)\`|(.+?))\\s*$`, "mu"),
  );
  const value = match?.[1] ?? match?.[2];
  const trimmed = value?.trim();
  return trimmed && trimmed.length > 0 ? trimmed : undefined;
}

function parseTreeMode(value: string | undefined): TreeMode | undefined {
  return value === "dedicated" || value === "shared" ? value : undefined;
}

function extractManagedBlock(text: string): string | undefined {
  const normalized = text.replaceAll("\r\n", "\n");
  const managedBlock = new RegExp(
    `${escapeForRegExp(TREE_IDENTITY_BEGIN)}[\\s\\S]*?${escapeForRegExp(TREE_IDENTITY_END)}`,
    "mu",
  );

  return normalized.match(managedBlock)?.[0];
}

function parseManagedTreeIdentity(
  text: string,
): Omit<ManagedTreeIdentity, "file" | "path"> | undefined {
  const block = extractManagedBlock(text);

  if (block === undefined) {
    return undefined;
  }

  const treeRepoName = readMarker(block, TREE_REPO_MARKER);

  if (treeRepoName === undefined) {
    return undefined;
  }

  const publishedTreeUrl = (() => {
    const value = readMarker(block, TREE_PUBLISHED_URL_MARKER);
    return value === "pending publish" ? undefined : value;
  })();

  return {
    ...(publishedTreeUrl ? { publishedTreeUrl } : {}),
    treeMode: parseTreeMode(readMarker(block, TREE_MODE_MARKER)),
    treeRepoName,
  };
}

function treeIdentityBlock(identity: TreeIdentityContract): string {
  return [
    TREE_IDENTITY_BEGIN,
    "## Tree Identity",
    "",
    "> Managed block — regenerated by `first-tree` tooling. Do not edit by hand.",
    "",
    `- **Tree repo:** \`${identity.treeRepoName}\``,
    ...(identity.treeMode ? [`- **Tree mode:** \`${identity.treeMode}\``] : []),
    `- **Published tree URL:** ${identity.publishedTreeUrl ? `<${identity.publishedTreeUrl}>` : "_pending publish_"}`,
    "",
    "<!--",
    `${TREE_IDENTITY_MARKER} managed-block-v1`,
    `${TREE_REPO_MARKER} \`${identity.treeRepoName}\``,
    ...(identity.treeMode ? [`${TREE_MODE_MARKER} \`${identity.treeMode}\``] : []),
    `${TREE_PUBLISHED_URL_MARKER} ${identity.publishedTreeUrl ? `\`${identity.publishedTreeUrl}\`` : "pending publish"}`,
    "-->",
    TREE_IDENTITY_END,
  ].join("\n");
}

function upsertManagedBlock(text: string, block: string): string {
  const normalized = ensureTrailingNewline(text.replaceAll("\r\n", "\n"));
  const managedBlock = new RegExp(
    `${escapeForRegExp(TREE_IDENTITY_BEGIN)}[\\s\\S]*?${escapeForRegExp(TREE_IDENTITY_END)}\\n?`,
    "mu",
  );

  if (managedBlock.test(normalized)) {
    return ensureTrailingNewline(normalized.replace(managedBlock, `${block}\n`));
  }

  const insertBefore = /^# Project-Specific Instructions\s*$/mu.exec(normalized);

  if (insertBefore && insertBefore.index >= 0) {
    return ensureTrailingNewline(
      [
        normalized.slice(0, insertBefore.index).trimEnd(),
        block,
        normalized.slice(insertBefore.index).trimStart(),
      ]
        .filter(Boolean)
        .join("\n\n"),
    );
  }

  const insertAfter = /<!-- END CONTEXT-TREE FRAMEWORK -->\s*/mu.exec(normalized);

  if (insertAfter && insertAfter.index >= 0) {
    const insertAt = insertAfter.index + insertAfter[0].length;
    return ensureTrailingNewline(
      [normalized.slice(0, insertAt).trimEnd(), block, normalized.slice(insertAt).trimStart()]
        .filter(Boolean)
        .join("\n\n"),
    );
  }

  return ensureTrailingNewline(`${normalized.trimEnd()}\n\n${block}`);
}

function writeIdentityFile(path: string, identity: TreeIdentityContract): SyncAction {
  const current = existsSync(path) ? readFileSync(path, "utf-8") : null;
  const next = upsertManagedBlock(current ?? "", treeIdentityBlock(identity));

  if (current === next) {
    return "unchanged";
  }

  writeFileSync(path, next);
  return current === null ? "created" : "updated";
}

export function readManagedTreeIdentity(root: string): ManagedTreeIdentity | undefined {
  for (const file of TREE_IDENTITY_FILES) {
    const path = join(root, file);

    if (!existsSync(path)) {
      continue;
    }

    const parsed = parseManagedTreeIdentity(readFileSync(path, "utf-8"));

    if (parsed !== undefined) {
      return {
        ...parsed,
        file,
        path,
      };
    }
  }

  return undefined;
}

export function findUpwardsManagedTreeIdentity(startDir: string): ManagedTreeIdentity | undefined {
  let currentDir = resolve(startDir);

  while (true) {
    const identity = readManagedTreeIdentity(currentDir);

    if (identity !== undefined) {
      return identity;
    }

    const parentDir = dirname(currentDir);

    if (parentDir === currentDir) {
      return undefined;
    }

    currentDir = parentDir;
  }
}

export function readTreeIdentityContract(root: string): TreeIdentityContract | undefined {
  const managedIdentity = readManagedTreeIdentity(root);

  if (managedIdentity !== undefined) {
    return managedIdentity;
  }

  const treeState = readTreeState(root);

  if (treeState === null) {
    return undefined;
  }

  return {
    ...(treeState.published?.remoteUrl ? { publishedTreeUrl: treeState.published.remoteUrl } : {}),
    treeMode: treeState.treeMode,
    treeRepoName: treeState.treeRepoName,
  };
}

export function syncTreeIdentityFiles(
  treeRoot: string,
  identity: TreeIdentityContract,
): SyncAction {
  let overallAction: SyncAction = "skipped";

  for (const file of TREE_IDENTITY_FILES) {
    const path = join(treeRoot, file);

    if (!existsSync(path)) {
      continue;
    }

    const action = writeIdentityFile(path, identity);
    if (action === "created" || action === "updated") {
      overallAction = action;
    } else if (overallAction === "skipped") {
      overallAction = action;
    }
  }

  return overallAction;
}
