/**
 * Gardener config loader.
 *
 * Reads `.claude/gardener-config.yaml` at the tree repo root and returns
 * a typed object. The config file is auto-generated by gardener tooling
 * so the format is predictable — we hand-roll the parser to avoid
 * pulling in a YAML dependency for a config this small.
 *
 * Supported shape:
 *   tree_repo: owner/name
 *   target_repos:
 *     - owner/repo-one
 *     - owner/repo-two
 *   modules:
 *     sync:
 *       enabled: true
 *     respond:
 *       enabled: false
 *     comment:
 *       enabled: true
 *
 * Keys not listed above are ignored. Comments (`# ...`) and blank lines
 * are skipped.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export interface ModuleToggle {
  enabled: boolean;
}

export interface GardenerConfig {
  tree_repo?: string;
  target_repos?: string[];
  modules?: {
    sync?: ModuleToggle;
    respond?: ModuleToggle;
    comment?: ModuleToggle;
  };
}

export type ModuleName = "sync" | "respond" | "comment";

const CONFIG_PATH_FROM_TREE_ROOT = join(".claude", "gardener-config.yaml");

function stripComment(line: string): string {
  // Allow `#` inside quoted values; strip otherwise.
  let inSingle = false;
  let inDouble = false;
  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i];
    if (ch === "'" && !inDouble) inSingle = !inSingle;
    else if (ch === '"' && !inSingle) inDouble = !inDouble;
    else if (ch === "#" && !inSingle && !inDouble) return line.slice(0, i);
  }
  return line;
}

function stripQuotes(value: string): string {
  const trimmed = value.trim();
  if (trimmed.length >= 2) {
    const first = trimmed[0];
    const last = trimmed[trimmed.length - 1];
    if ((first === '"' && last === '"') || (first === "'" && last === "'")) {
      return trimmed.slice(1, -1);
    }
  }
  return trimmed;
}

function parseScalar(raw: string): string | boolean | number {
  const value = stripQuotes(raw);
  if (value === "true") return true;
  if (value === "false") return false;
  const num = Number(value);
  if (value !== "" && !Number.isNaN(num) && /^-?\d+(?:\.\d+)?$/.test(value)) {
    return num;
  }
  return value;
}

function countIndent(line: string): number {
  let i = 0;
  while (i < line.length && line[i] === " ") i += 1;
  return i;
}

interface ParsedLine {
  indent: number;
  raw: string;
  isList: boolean;
}

function prepLines(text: string): ParsedLine[] {
  const out: ParsedLine[] = [];
  for (const original of text.split(/\r?\n/)) {
    const stripped = stripComment(original);
    if (stripped.trim() === "") continue;
    const indent = countIndent(stripped);
    const body = stripped.slice(indent);
    out.push({ indent, raw: body, isList: body.startsWith("- ") || body === "-" });
  }
  return out;
}

/**
 * Very small YAML subset parser. Supports:
 *   - mappings of `key: value` (nested by indentation)
 *   - list items `- value` (scalars only)
 *   - quoted/unquoted scalars, booleans, numbers
 *
 * Anything it doesn't understand is silently dropped — the config file
 * is auto-generated and small, so this is acceptable.
 */
function parseYamlSubset(text: string): Record<string, unknown> {
  const lines = prepLines(text);
  let cursor = 0;

  const parseBlock = (baseIndent: number): unknown => {
    const mapping: Record<string, unknown> = {};
    const list: unknown[] = [];
    let isList: boolean | null = null;

    while (cursor < lines.length) {
      const line = lines[cursor];
      if (line.indent < baseIndent) break;
      if (line.indent > baseIndent) {
        // Should not happen for well-formed input; skip to avoid loops.
        cursor += 1;
        continue;
      }

      if (line.isList) {
        if (isList === false) break;
        isList = true;
        const after = line.raw.slice(2).trim();
        cursor += 1;
        if (after === "") {
          const child = parseBlock(baseIndent + 2);
          list.push(child);
        } else {
          list.push(parseScalar(after));
        }
        continue;
      }

      if (isList === true) break;
      isList = false;

      const colonIdx = line.raw.indexOf(":");
      if (colonIdx < 0) {
        cursor += 1;
        continue;
      }
      const key = line.raw.slice(0, colonIdx).trim();
      const rest = line.raw.slice(colonIdx + 1).trim();
      cursor += 1;

      if (rest === "") {
        // Look ahead: nested mapping or list?
        if (cursor < lines.length && lines[cursor].indent > baseIndent) {
          mapping[key] = parseBlock(lines[cursor].indent);
        } else {
          mapping[key] = null;
        }
      } else {
        mapping[key] = parseScalar(rest);
      }
    }

    return isList ? list : mapping;
  };

  const top = parseBlock(0);
  if (top && typeof top === "object" && !Array.isArray(top)) {
    return top as Record<string, unknown>;
  }
  return {};
}

function coerceStringArray(value: unknown): string[] | undefined {
  if (!Array.isArray(value)) return undefined;
  const out: string[] = [];
  for (const entry of value) {
    if (typeof entry === "string") out.push(entry);
    else if (typeof entry === "number" || typeof entry === "boolean") {
      out.push(String(entry));
    }
  }
  return out;
}

function coerceModuleToggle(value: unknown): ModuleToggle | undefined {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return undefined;
  }
  const raw = (value as Record<string, unknown>).enabled;
  if (typeof raw === "boolean") return { enabled: raw };
  if (typeof raw === "string") {
    if (raw === "true") return { enabled: true };
    if (raw === "false") return { enabled: false };
  }
  return undefined;
}

function coerceConfig(raw: Record<string, unknown>): GardenerConfig {
  const config: GardenerConfig = {};
  if (typeof raw.tree_repo === "string") config.tree_repo = raw.tree_repo;
  const targets = coerceStringArray(raw.target_repos);
  if (targets) config.target_repos = targets;

  if (
    raw.modules &&
    typeof raw.modules === "object" &&
    !Array.isArray(raw.modules)
  ) {
    const modulesRaw = raw.modules as Record<string, unknown>;
    const modules: GardenerConfig["modules"] = {};
    const sync = coerceModuleToggle(modulesRaw.sync);
    const respond = coerceModuleToggle(modulesRaw.respond);
    const comment = coerceModuleToggle(modulesRaw.comment);
    if (sync) modules.sync = sync;
    if (respond) modules.respond = respond;
    if (comment) modules.comment = comment;
    config.modules = modules;
  }
  return config;
}

/**
 * Load `.claude/gardener-config.yaml` from the given tree root.
 * Returns `null` when the file is missing or unreadable — callers
 * should treat that as "no config, all modules default to enabled".
 */
export function loadGardenerConfig(treeRoot: string): GardenerConfig | null {
  const path = join(treeRoot, CONFIG_PATH_FROM_TREE_ROOT);
  if (!existsSync(path)) return null;
  let text: string;
  try {
    text = readFileSync(path, "utf-8");
  } catch {
    return null;
  }
  try {
    const raw = parseYamlSubset(text);
    return coerceConfig(raw);
  } catch {
    return null;
  }
}

/**
 * Returns true when the named module should run. Defaults to true when
 * the config is missing, the `modules` section is absent, or the
 * specific module toggle is unspecified.
 */
export function isModuleEnabled(
  config: GardenerConfig | null,
  module: ModuleName,
): boolean {
  if (!config || !config.modules) return true;
  const toggle = config.modules[module];
  if (!toggle) return true;
  return toggle.enabled !== false;
}
