#!/usr/bin/env bash
#
# Build the FirstTreeTray.app bundle from the SwiftPM executable.
#
# Output: apps/tray-mac/.build/FirstTreeTray.app
#
# Usage:
#   ./scripts/build-tray-app.sh           # debug build
#   ./scripts/build-tray-app.sh release   # release build (smaller, faster)
#

set -euo pipefail

CONFIG="${1:-debug}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TRAY_DIR="$(dirname "$SCRIPT_DIR")"
cd "$TRAY_DIR"

# Compile the Swift binary.
echo "→ Building Swift target ($CONFIG)..."
if [ "$CONFIG" = "release" ]; then
  swift build -c release
  BUILD_BIN=".build/release/FirstTreeTray"
else
  swift build
  # SwiftPM places debug builds under arch-specific dir; resolve it.
  BUILD_BIN="$(find .build -type f -name FirstTreeTray -perm +111 | head -1)"
fi

if [ ! -f "$BUILD_BIN" ]; then
  echo "ERROR: build did not produce a binary at $BUILD_BIN"
  exit 1
fi

# Locate the bundled resources (FirstTreeIcon.png etc.) generated by SwiftPM.
RES_BUNDLE="$(find .build -maxdepth 3 -name 'FirstTreeTray_FirstTreeTray.bundle' -type d | head -1)"
if [ -z "$RES_BUNDLE" ]; then
  echo "ERROR: SwiftPM resource bundle not found"
  exit 1
fi

# Build the .app bundle layout.
APP=".build/FirstTreeTray.app"
echo "→ Assembling .app bundle at $APP..."
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$BUILD_BIN" "$APP/Contents/MacOS/FirstTreeTray"
cp -R "$RES_BUNDLE" "$APP/Contents/Resources/"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>FirstTreeTray</string>
  <key>CFBundleDisplayName</key><string>first-tree</string>
  <key>CFBundleIdentifier</key><string>com.first-tree.tray</string>
  <key>CFBundleVersion</key><string>0.1</string>
  <key>CFBundleShortVersionString</key><string>0.1</string>
  <key>CFBundleExecutable</key><string>FirstTreeTray</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
  <key>LSUIElement</key><true/>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

echo "✓ Built $APP"

# Developer hints: only show when run interactively (not when invoked from
# install-tray.sh during `scan install`).
if [ -t 1 ] && [ "${FIRST_TREE_TRAY_BUILD_QUIET:-0}" = "0" ]; then
  echo ""
  echo "To run:  open $APP"
  echo "To install for the user: cp -R $APP ~/.first-tree/tray/"
fi
